spring:
  application:
    name: nutric
  datasource:
    url: ${POSTGRES_CONNECTION_STRING}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.rumetshofer.dev/realms/nutric

server:
  error:
    whitelabel:
      enabled: false
  port: 8081

yazio:
  api:
    urlBase: https://yzapi.yazio.com
    oauthTokenUrl: /v8/oauth/token
    searchUrl: /v16/products/search
  auth:
    clientId: ${YAZIO_API_CLIENT_ID}
    clientSecret: ${YAZIO_API_CLIENT_SECRET}
    user: ${YAZIO_API_USER}
    password: ${YAZIO_API_PASSWORD}